### ISSUE TITLE
Update for Create 2.0

### ISSUE THREAD

**Issue by alexispurslane** [17JamesH/Botball-LACT-Libraries#2]
No offense to your code (Its really good code), but I was thinking that the code could use some refactoring, and while I'm at it, I could update whatever needs updating for the new Create, if someone could point me to some documentation for the new Create.

**Comment by 17JamesH** [comment]
Thanks for offering to do this! The documentation for the new Create can be found at http://www.irobot.com/~/media/MainSite/PDFs/About/STEM/Create/create_2_Open_Interface_Spec.pdf . I'm not entirely finished with the library, as I still have to do the position functions and driving functions, but a refactor would be much appreciated. Help with the drive and position functions would be great too.

**Comment by alexispurslane** [comment]
I finished the reactor and merged it. What do you think?

**Comment by 17JamesH** [comment]
Taking a look right now.

**Comment by alexispurslane** [comment]
I want to help with the drive and position functions, but I don't know anything about them, what we need to add, or anything... Could you walk me through the updates and things we need to change and stuff? Just give me a few pointers (as in help, not `0xAbb545`).

**Comment by alexispurslane** [comment]
(:

**Comment by alexispurslane** [comment]
By the way, your email address keeps coming back with `Delivery to the following recipient failed permanently: 17jamesh@student.harker.org`, do you have another email address or something?

**Comment by 17JamesH** [comment]
students instead of student

**Comment by alexispurslane** [comment]
Aha! Thanks.

**Comment by 17JamesH** [comment]
The get position functions should be pretty straightforward. However, the position counter loops back to 0 once it hits the maximum value and vice versa, so accounting for that is probably the hardest part of the program. The drive functions that need to be updated are the left and right turn functions, which I plan to adapt from drive.h.

**Comment by alexispurslane** [comment]
How about I do the get position functions, and you handle the drive functions, since I'm less experienced. 
- Where exactly are the get position functions, or are we creating them, and if so where do I put them? 
- Also, can you explain what they do / how they work, or where they are in the manual?

Sorry, I'm completely unfamiliar (aka total n00b) with the low-level Create stuff.

**Comment by 17JamesH** [comment]
The function you are working on is called create_wait_angle, and while the documentation for what the function should do is there, there isn't much code in the function. The way the function previously worked was using: 
  create_write_byte(157);
  create_write_int(angle);
however, the wait angle command (157) has been removed with the new create, so we need to manually implement this using the left and right encoders commands (43,44), by getting the encoder positions and waiting until a certain distance has been passed. Some other commands you will have to use are create_read_(un)signed, in order to read the value that the encoder outputs. I believe the Create stores outputs using a stack, though I could be wrong and it uses a queue.

**Comment by 17JamesH** [comment]
Ah forgot to add, the create wait dist function hasn't been implemented either.

**Comment by alexispurslane** [comment]
Okay, I'll start on the `create_wait_angle`!

**Comment by 17JamesH** [comment]
After thinking about it, create_wait_angle will probably require some trigonometry, and sounds like it will be a pain to implement, so I would suggest working on create_wait_dist first.

**Comment by 17JamesH** [comment]
I've thought of a general formula we can use to find the angle. Radius1 = distance from center of turn to closer wheel. Radius2 = diameter + Radius1 or the distance from the center of the turn to the farther wheel. Angle = angle of turn(in radians). Dist1 = distance traveled by closer wheel. Dist2 = distance traveled by farther wheel. Angle \* Radius1 = Dist1 and Angle \* Radius2 = Dist2, so Dist1/Radius1 = Dist2/Radius2, and we can use either Dist/Radius pairs to find the Angle.

**Comment by alexispurslane** [comment]
Ok. Yeah, I have no idea how to do trig.

**Comment by 17JamesH** [comment]
```
Dist1 / Radius1 = Dist2 / (Radius1 + diameter).
Radius1 / Dist2 + diameter/Dist2 = Radius1 / Dist1.
Radius1/Dist2 - Radius1/Dist1 = -diameter/Dist2.
Radius1Dist2 - Radius1Dist1 = diameterDist1.
Radius1(Dist2-Dist1) = diameter * Dist1.
Radius1 = (diameter * Dist1) / (Dist2 - Dist1).

so therefore, Angle = (Dist2 - Dist1)*Dist1 / (diameter * Dist1).
Assuming Dist1 isn't 0, the formula for the Angle of a turn should be (Dist2-Dist1) / diameter.
```

**Comment by alexispurslane** [comment]
With `create_wait_dist`, what should it do if the robot is turning (i.e. one wheel is at a different velocity than the other)?

**Comment by 17JamesH** [comment]
with create_wait_dist, I was thinking once the average distance traveled by the two wheels travels the indicated distance.

**Comment by alexispurslane** [comment]
OK, that's what I was thinking! Cool.

**Comment by christopherdumas** [comment]
I use `create_read_signed` to read a Data Byte address, right?

**Comment by alexispurslane** [comment]
OK, finished updating `create_wait_dist`. I havn't checked it (I don't have a robot to check it on), though.

**Comment by 17JamesH** [comment]
I'll give all the functions a test on the old create a bit before the build season starts. Thanks so much for the help! The function looks great so far. I forgot if the reason I didn't use #19 and #20 instead of encoders was because of negligence or because of accuracy issues, so I'm going to check with one of the graduated botballers. It would be great if there weren't any accuracy issues, because it would make our job a whole lot easier.

**Comment by alexispurslane** [comment]
Oh, by the way, we should start using version tags so that we can keep track of milestones and versions. So for instance, we can say that this is version `1.0` and for version `1.1`  we refactored, and for `2.0` we updated it for the iRobot Create 2.0. I'll start setting that up.

**Comment by 17JamesH** [comment]
Alright

**Comment by alexispurslane** [comment]
OK, check it out: https://github.com/17JamesH/Botball-LACT-Libraries/releases
Each version points to a specific milestone as a commit. Now, also, if we need to roll back, it'll be easier.

**Comment by alexispurslane** [comment]
OK, so I guess I'll start working on `create_wait_angle` now.

**Comment by alexispurslane** [comment]
OK, I finished `create_wait_angle`. I also merged the Pull Request.

**Comment by alexispurslane** [comment]
Are there any other functions that need to be changed/updated in any way?

**Comment by alexispurslane** [comment]
I'm in the process of slowly looking over all the functions in the `createDrive.c` file and checking them with the Open Interface documentation to make sure they comply.

**Comment by 17JamesH** [comment]
I think we're done here. All of the functions should be updated and ready for the new create.

**Comment by alexispurslane** [comment]
```
──────█▀▄─▄▀▄─▀█▀─█─█─▀─█▀▄─▄▀▀▀─────
──────█─█─█─█──█──█▀█─█─█─█─█─▀█─────
──────▀─▀──▀───▀──▀─▀─▀─▀─▀──▀▀──────
─────────────────────────────────────
───────────────▀█▀─▄▀▄───────────────
────────────────█──█─█───────────────
────────────────▀───▀────────────────
─────────────────────────────────────
─────█▀▀▄─█▀▀█───█──█─█▀▀─█▀▀█─█▀▀───
─────█──█─█──█───█▀▀█─█▀▀─█▄▄▀─█▀▀───
─────▀▀▀──▀▀▀▀───▀──▀─▀▀▀─▀─▀▀─▀▀▀───
─────────────────────────────────────
─────────▄███████████▄▄──────────────
──────▄██▀──────────▀▀██▄────────────
────▄█▀────────────────▀██───────────
──▄█▀────────────────────▀█▄─────────
─█▀──██──────────────██───▀██────────
█▀──────────────────────────██───────
█──███████████████████───────█───────
█────────────────────────────█───────
█────────────────────────────█───────
█────────────────────────────█───────
█────────────────────────────█───────
█────────────────────────────█───────
█▄───────────────────────────█───────
▀█▄─────────────────────────██───────
─▀█▄───────────────────────██────────
──▀█▄────────────────────▄█▀─────────
───▀█▄──────────────────██───────────
─────▀█▄──────────────▄█▀────────────
───────▀█▄▄▄──────▄▄▄███████▄▄───────
────────███████████████───▀██████▄───
─────▄███▀▀────────▀███▄──────█─███──
───▄███▄─────▄▄▄▄────███────▄▄████▀──
─▄███▓▓█─────█▓▓█───████████████▀────
─▀▀██▀▀▀▀▀▀▀▀▀▀███████████────█──────
────█─▄▄▄▄▄▄▄▄█▀█▓▓─────██────█──────
────█─█───────█─█─▓▓────██────█──────
────█▄█───────█▄█──▓▓▓▓▓███▄▄▄█──────
────────────────────────██──────────
────────────────────────██───▄███▄───
────────────────────────██─▄██▓▓▓██──
───────────────▄██████████─█▓▓▓█▓▓██▄
─────────────▄██▀───▀▀███──█▓▓▓██▓▓▓█
─▄███████▄──███───▄▄████───██▓▓████▓█
▄██▀──▀▀█████████████▀▀─────██▓▓▓▓███
██▀─────────██──────────────██▓██▓███
██──────────███──────────────█████─██
██───────────███──────────────█─██──█
██────────────██─────────────────█───
██─────────────██────────────────────
██─────────────███───────────────────
██──────────────███▄▄────────────────
███──────────────▀▀███───────────────
─███─────────────────────────────────
──███────────────────────────────────
```

**Comment by alexispurslane** [comment]
LOL. I didnt even know that was a thing on the internet.

**Comment by alexispurslane** [comment]
I'll finish checking though.

**Comment by alexispurslane** [comment]
I also found some errors in `singing.h` and went ahead and refactored it as well as fixing the errors.

**Comment by alexispurslane** [comment]
I'll close this issue now, I guess.
